baseURL = "https://yhnhefeng.github.io/"
languageCode = "en-us"
title = "hefeng's blog"
theme = "FixIt"
defaultContentLanguage = "zh-cn"

[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

[menu]
  [[menu.main]]
    identifier = ""
    # FixIt 0.2.14 | 新增 父级菜单项的标识符 (identifier)
    parent = ""
    # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
    pre = ""
    # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
    post = ""
    name = ""
    url = ""
    # 当你将鼠标悬停在此菜单链接上时，将显示的标题
    title = ""
    weight = 1
    # FixIt 0.2.14 | 新增 向菜单项添加用户定义的内容
    [menu.main.params]
      # 添加 CSS 类到菜单项
      class = ""
      # 是否为草稿菜单，类似草稿页面
      draft = false
      # FixIt 0.2.16 | 新增 添加 fontawesome 图标到菜单项
      icon = ""
      # FixIt 0.2.16 | 新增 设置菜单项类型，可选值：["mobile", "desktop"]
      type = ""
      # FixIt 0.3.9 | 新增 是否显示子菜单项分割线
      divided = false